name: dpg_app
description: A Flutter app integrated with Rasa chatbot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1  
  http: ^1.4.0
  speech_to_text: ^6.3.0 # For voice-to-text (STT)
  flutter_tts: ^3.8.5    # For text-to-speech (TTS)
  permission_handler: ^11.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
